### ISSUE TITLE
The Tea Time

### ISSUE THREAD

**Issue by syorito-hatsuki** [GalievDev/ManyFlowers#10]
# Tea ingredients

- [ ] Anis Seed
- [ ] Bird Cherry Flower
- [ ] Cardamom Chilipepper Oil
- [ ] Chamomile
- [ ] Cinnamon
- [ ] Cloves
- [ ] Dandelion
- [ ] Dried Apple Pieces
- [ ] Dried Pineapple
- [ ] Eucalyptus Leaves
- [ ] Fennel
- [ ] Ginder
- [ ] Green Chinese Sencha Tea
- [ ] Green Gunpowder Tea
- [ ] Green Rooibos
- [ ] Heather
- [ ] Hibiscus
- [ ] India-Ceylon Tea
- [ ] Jasmine Flower
- [ ] Lavender
- [ ] Lemon Verbena
- [ ] Lemongrass
- [ ] Licorice Root
- [ ] Lily
- [ ] Lime Flower
- [ ] Mate
- [ ] Mint Leaves
- [ ] Natural Bergamot Oil
- [ ] Natural Citrus Flavor
- [ ] Natural Flavor
- [ ] Natural Ginger Oil
- [ ] Natural Mango Flavor
- [ ] Natural Passion Fruit Flavor
- [ ] Natural Pear Flavor
- [ ] Natural Strawberry-Vanilla Flavor
- [ ] Nettle
- [ ] Orange
- [ ] Papaya Pieces
- [ ] Peony
- [ ] Peppermint Leaves
- [ ] Pieces of Apple
- [ ] Pineapple
- [ ] Rose Hip
- [ ] Rose Petals
- [ ] Strawberry Leaves
- [ ] Sunflower
- [ ] Turmeric
- [ ] Valerian Root
- [ ] Vervain
- [ ] White Tea

# Teas
(DRAFT)

**Comment by GalievDev** [comment]
It will be in a new mod - https://github.com/GalievDev/delicious-teas/issues/1

**Comment by GalievDev** [comment]
It will be in a new mode - https://github.com/GalievDev/delicious-teas/issues/1
