### ISSUE TITLE
Opt-out of sending analytics to fstats.dev via config file.

### ISSUE THREAD

**Issue by hatkidchan** [GalievDev/ManyFlowers#13]
![image](https://github.com/GalievDev/many-flowers/assets/35804000/257685c4-7d42-425b-9c98-bfb538372cce)
![image](https://github.com/GalievDev/many-flowers/assets/35804000/c479d3fa-5e0a-489c-ab3d-2d20769dcf1e)
This is a little annoying, plus I just don't want to share any data about my private server. No other mod does that and those that do, let me opt out of sending any analytics quite easily.

Sure, I can build it from source with analytics chopped out, but I'd rather have it more configurable.

**Comment by syorito-hatsuki** [comment]
fStats have their own config file and you can disable it from it

**Comment by hatkidchan** [comment]
My bad, sorry
