### ISSUE TITLE
[FEATURE] Remove Ducky Updater Lib dependency

### ISSUE THREAD

**Issue by nco2k** [GalievDev/ManyFlowers#7]
any chance you could get rid of the Ducky Updater Lib dependency, and use Mod Menu's update checker instead? the Ducky Updater Lib gives out an ingame message, while Mod Menu adds a small icon next to the name. i prefer the latter option, because its less intrusive.

**Comment by GalievDev** [comment]
No, I won't remove it because modpacks need to support up-to-date
