### ISSUE TITLE
Missing small/tall flower tags in the mod

### ISSUE THREAD

**Issue by TelepathicGrunt** [GalievDev/ManyFlowers#8]
It'll be best to tag your flowers in the appropriate block and item tags for best compat with other mods and to work with vanilla bees.

You can find the flower tags here
https://minecraft.wiki/w/Tag

Short summary of the tags
`minecraft:small_flowers` <- 1 block tall normal flowers
`minecraft:tall_flowers` <- 2 block tall flowers
`minecraft:flowers` <- all other kinds of flowers

**Comment by GalievDev** [comment]
Thank you! It will be done in the next update.

**Comment by GalievDev** [comment]
https://modrinth.com/mod/many-flowers/version/OIIWERoL
