### ISSUE TITLE
Remove modmenu as a dependency

### ISSUE THREAD

**Issue by akai-hana** [GalievDev/ManyFlowers#9]
When setting up a server with this mod, it won't launch until I add modmenu on the server, and modmenu is unsupported serverside. The server will still work, but it will have an extra pointless mod in it.

**Comment by GalievDev** [comment]
Hello, which is your Minecraft version?

**Comment by GalievDev** [comment]
Are you here? I should know your Minecraft version, because modmenu is optional on 1.20+ versions

**Comment by akai-hana** [comment]
Hey, sorry for the delay.

I'm on 1.19.2. I'm playing on a 1.19 modpack.

**Comment by GalievDev** [comment]
OK, today I will release a new update with a fix this

**Comment by akai-hana** [comment]
TY! Much appreciated.

**Comment by GalievDev** [comment]
Fixed - https://modrinth.com/mod/many-flowers/version/1.19.2-2.3
